### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by svenkreiss** [svenkreiss/pysparkling#134]
Any particular opinion on when would be a good time for a new release, @tools4origins ?
There is no rush on my side.

**Comment by tools4origins** [comment]
Hmm we may want to do a release before SQL string parsing as it will lead to a lot of additional work and may take a bit of time before being stable,

If so, now would be a good time, would that work for you?

**Comment by svenkreiss** [comment]
Yes, sure. I'll aim for end of this week then.

**Comment by svenkreiss** [comment]
Hi @tools4origins , I hope you are doing well. There was a new release some days ago. I wanted to mention also to you that I moved the build system to GitHub Actions that test on Mac and Windows and that now also do automatic deploys to pypi for every new GitHub release.
