### ISSUE TITLE
Warning when running tests

### ISSUE THREAD

**Issue by alexprengere** [svenkreiss/pysparkling#22]
`nosetests` is failing with the following error:
```
nosetests: error: Error reading config file 'setup.cfg': 
no such option 'with-doctest-ignore-unicode'
```

When using `python setup.py test`, it works but still we get a warning:
```
RuntimeWarning: Option 'with-doctest' in config file 'setup.cfg' ignored:
excluded by runtime environment
```
Can we remove this option, or am I missing some libraries to make it work?

**Comment by svenkreiss** [comment]
Quick answer: run `pip install` for all of these by hand

```
    tests_require=[
        'nose>=1.3.4',
        'futures>=3.0.1',
        'cloudpickle>=0.1.0',
        'doctest-ignore-unicode>=0.1.2',
    ]
```

Long answer: this should happen automatically when you run tests. Not sure why it doesn't but I have also seen this problem before.

**Comment by alexprengere** [comment]
Weird, I did just that and still get the error.

**Comment by svenkreiss** [comment]
Hmm, I can reproduce your error, but I can fix it with `pip install doctest-ignore-unicode`. Then `nosetests` runs fine. 

Don't run `python setup.py test`. If you want to run through `setup.py`, run `python setup.py nosetests`.

**Comment by svenkreiss** [comment]
Actually, it seems there is a long history of discussions why `tests_require` does not work and whether it's setuptools's or nose's fault.

I can make these dependencies an `extra`. Which would mean running `pip install -e .[tests]` when working on the code locally. Given that the current dependencies are broken, maybe that is the way to go. I have seen it in another well maintained package.

**Comment by alexprengere** [comment]
Ok I see. Personally I use `pytest` and `tox` to manage tests running in separate virtualenvs.
`tox` installs all tests dependencies before running tests and I do not put them in the `setup.py` (example [here](https://github.com/alexprengere/currencyconverter)).

**Comment by svenkreiss** [comment]
Just merged in a change how test dependencies are handled. TravisCI also uses that now. It's documented in the `Development` section at the bottom of the readme file. I hope it works for you too (reopen if not).
