### ISSUE TITLE
Add accumulators

### ISSUE THREAD

**Issue by alexprengere** [svenkreiss/pysparkling#25]
This issue is to discuss the addition of the [accumulators](https://spark.apache.org/docs/0.9.0/api/pyspark/index.html) in pysparkling. Very basically, these are shared variables between workers.

**Comment by svenkreiss** [comment]
Sounds interesting. 

Out of curiosity, do you need them in your own code or do you envision this to be a step to simplify the logic of some RDD methods?

**Comment by alexprengere** [comment]
I need accumulators to get closer to feature parity with `pyspark`, to be able to switch easily between the two for testing purposes. I use accumulators to track global metrics accross all workers. Today I mock them with a simple class:
```python
class Accumulator(object):
    """This is a mocked version of the real pyspark.accumulators
    """
    def __init__(self, value):
        self.value = value

    def __iadd__(self, inc):
        self.value += inc
        return self
```
The source code for accumulators in Spark is [here](https://spark.apache.org/docs/1.1.0/api/python/pyspark.accumulators-pysrc.html). I guess some boilerplate code can be copied to `pysparkling` to emulate the same behavior.

**Comment by svenkreiss** [comment]
Another source link is [here](https://github.com/apache/spark/blob/master/python/pyspark/accumulators.py).

The real implementation that supports parallelization would be a bit more complex (but certainly doable). Through the context, a `context.accumulator()` call would create an instance of `Accumulator` but also register it in an accumulator-registry. Those instances would have to be serialized out to workers in a map operation along with everything else and merged back on the driver when done.

I guess those would be useful for collecting data about the distributed operations. We already collect some timing information in `context._stats`, but Accumulators could be used to do this a bit nicer and expose an interface to the user to add to that.
