### ISSUE TITLE
Including RDDs in RDDs should probably throw an error

### ISSUE THREAD

**Issue by pganssle** [svenkreiss/pysparkling#37]
In Spark, it's not possible to make references to a context or an RDD from the executor threads, so if you try to parallelize something with an RDD in it, you get an error:

``` python
>>> o = sc.parallelize(sc.parallelize(range(x) for x in range(5))

[ Traceback ]

Exception: It appears that you are attempting to reference SparkContext from a 
broadcast variable, action, or transforamtion. SparkContext can only be used
on the driver, not in code that it run on workers. For more information,
see SPARK-5063.
```

In pysparkling, no such distinction is made:

``` python
from pysparkling import Context
sc = Context()
o = sc.parallelize(sc.parallelize(range(x)) for x in range(5))
o.map(lambda x: x.collect()).collect()
```

Returns:

```
[[], [0], [0, 1], [0, 1, 2], [0, 1, 2, 3]]
```

I suppose this is good from a certain perspective, but I tend to use pySparkling for first-pass testing on systems without a Spark instance set up. It would be nice if there were a way to specify that it should strictly maintain Spark's behavior (this way if I accidentally add in a reference to a context or something, it'll break early).

**Comment by svenkreiss** [comment]
I like the idea of a `strict` mode for pyspark compatibility.

**Comment by svenkreiss** [comment]
Thanks for the detailed report. This is now implemented.
