### ISSUE TITLE
Supporting SQL/DataFrame ?

### ISSUE THREAD

**Issue by snuderl** [svenkreiss/pysparkling#47]
Hi.

Is there any intention of supporting spark DataFrames? I would be interested in helping out if you ever decide to go that way.

**Comment by svenkreiss** [comment]
Supporting DataFrames would be great. I haven't looked into it, because I
couldn't even decide whether it should be API compatible with PySpark or a
seamless interface to pandas. I don't know whether it can be both.

What do you think?

**Comment by snuderl** [comment]
My motivation for this is being able to unit test the Spark code so I would prefer api parity with PySpark.

Getting both at the same time would probably be much harder to achieve but it might be possible with some python hacks. TBH I don't have enough knowledge about Pandas to say for sure.

**Comment by wearpants** [comment]
+1 to Spark compatiblity - similarly interested in using this for our Spark unittests, which are ZOMG slow

**Comment by soumyadsanyal** [comment]
- Also voting for compatibility with PySpark Dataframes and SparkSQL APIs.

- @svenkreiss Is there a `CONTRIBUTING` doc for this project?

**Comment by nickray** [comment]
This would be great. Definitely the PySpark dataframes, not Pandas, due to how NULL is handled.

**Comment by daniel-cortez-stevenson** [comment]
+1 on this. Any suggestions or desire to collaborate on this?

**Comment by tools4origins** [comment]
Hi @daniel-cortez-stevenson, 

I saw your message today but created a branch for that about when you wrote it.

I am (quite actively) working on it in https://github.com/tools4origins/pysparkling/tree/feat/dataframe

**Comment by daniel-cortez-stevenson** [comment]
Hey @tools4origins 

Great, I'll take a look. Don't know how active I can be right now -- but this is certainly a big interest for me. We can talk there!

**Comment by talgo10** [comment]
@daniel-cortez-stevenson I would like to mention that would be great solution for running ML Pipelines with custom pyspark transformers with low-latency response (HTTP endpoints).
Currently, MLeap can't solve this and probably won't solve this.

Would love to collaborate on this :)

**Comment by stoney95** [comment]
Hi,

is there still any activity? As far as I can see, the branch https://github.com/tools4origins/pysparkling/tree/feat/sparkSQL has not been merged to master and is therefore not integrated to the package so far.

Would be glad to have a sqlContext in pysparkling for unit-testing as well
