### ISSUE TITLE
Anonymous Connection to Public S3 buckets

### ISSUE THREAD

**Issue by samuelchase** [svenkreiss/pysparkling#50]
S3 buckets can be made public, and with boto you can now connect to such buckets without providing an AWS Credentials.

pysparkling currently requires AWS Credentials, when connecting for any connection to S3 to be set as Environment Variables.

To connect to S3 anonymously you can do the following with boto.

boto.connect_s3(anon=True)

It would be great if pysparkling also allowed this when reading files from public S3 buckets.

**Comment by svenkreiss** [comment]
I hope this helps: http://pysparkling.trivial.io/en/latest/api_fileio.html#pysparkling.fileio.fs.S3
Let me know if there is still a problem.
