### ISSUE TITLE
RDD.fullOuterJoin is not implemented

### ISSUE THREAD

**Issue by pganssle** [svenkreiss/pysparkling#7]
According to [the PySpark documentation](https://spark.apache.org/docs/latest/api/python/pyspark.html#pyspark.RDD.fullOuterJoin), `RDD` should implement ``fullOuterJoin``.

MWE adapted from the PySpark documentation:
```python
from pysparkling import Context
sc = Context()
x = sc.parallelize([("a", 1), ("b", 4)])
y = sc.parallelize([("a", 2), ("c", 8)])
assert sorted(x.fullOuterJoin(y).collect()) == [('a', (1, 2)), ('b', (4, None)), ('c', (None, 8))]
```
I can make a PR implementing this in the relatively near future.

**Comment by svenkreiss** [comment]
Good find. That PR would be very much appreciated.

**Comment by pganssle** [comment]
I have it implemented the same way the other joins are implemented, just waiting on sign-off from my employer and I'll make the PR. The implementation I used still suffers from #8, but I can maybe fix that as well.

**Comment by svenkreiss** [comment]
This is now in pysparkling 0.3.7 on pypi. Thanks again.
