### ISSUE TITLE
Second argument to context.parallelize is numSlices, not numPartitions

### ISSUE THREAD

**Issue by SWu** [svenkreiss/pysparkling#75]
I have no idea why pyspark uses different terminology, but the optional second argument to parallelize is `numSlices`, not `numPartitions`. See: https://spark.apache.org/docs/latest/api/python/pyspark.html#pyspark.SparkContext.parallelize

**Comment by SWu** [comment]
Why was this closed? Won't fix?

**Comment by svenkreiss** [comment]
No, my mistake. This should get fixed.

**Comment by tools4origins** [comment]
Hello,

As to the why, [Spark java documentation](https://spark.apache.org/docs/latest/rdd-programming-guide.html#parallelized-collections) specifies: 

> some places in the code use the term slices (a synonym for partitions) to maintain backward compatibility.

Renaming the parameter is easy to implement but break backward compatibility on pysparkling side on call made with keyword parameters.

It is also possible to have an API `parallelize(self, c, numSlices=None, numPartitions=None)` which uses numSlices if defined else numPartitions.

I would say that the first option is better even though it breaks calls like `sc.parallelize([...] numPartitions=2)`: Such calls should not appear often and as they will never be compatible with PySpark pysparkling should prevent the user from doing that.
