### ISSUE TITLE
Coalesce without shuffle can increase the number of partitions

### ISSUE THREAD

**Issue by tools4origins** [svenkreiss/pysparkling#88]
Hello,

In spark, when the parameter `shuffle` is False, `coalesce` merges partitions which result in partitions of unequal size and prevent the number of partitions from increasing. On the other hand as it doesn't trigger a shuffle of the data it is often faster.

I do not know if the merge should be implemented, but the current implementation lead to increase in the number of partition which can be disturbing & lead to unexpected behaviour,

Reproduction:
Using pyspark:
```python
>>> sc.parallelize([1, 2, 3], 2).coalesce(4).getNumPartitions()
2
```

Using pysparkling:
```python
>>> sc.parallelize([1, 2, 3], 2).coalesce(4).getNumPartitions()
2
```

Suggested fix: use `min(numPartitions, self.getNumPartitions())` in `rdd.coalesce` when `shuffle` is `False`.

**Comment by svenkreiss** [comment]
Keep open. 

Sorry @tools4origins, this got lost on my side. Will get back to this in the next few days.
