### ISSUE TITLE
Link to documentation leads to author's personal page instead

### ISSUE THREAD

**Issue by notnami** [svenkreiss/pysparkling#98]
The link to documentation in README.rst redirects to the author's personal page instead.

Is there a hosted version of the docs?

**Comment by svenkreiss** [comment]
This was a misconfigured DNS entry. Should be working now or as soon as the DNS change has propagated. Thanks for reporting.

**Comment by svenkreiss** [comment]
And another issue forward from http to https. Changed the link to point directly to https. It should work now.
